# Dependencies
markdown:           redcarpet
highlighter:        pygments

# Permalinks
permalink:          /:title.html

# Setup
title:              Colin Seymour
tagline:            You Know This Boogie Is For Real
meta_description:   "lildude rocking the tech world."
baseurl:            /
url:                https://colinseymour.co.uk
logo:               true
#paginate:           15   # Disable pagination

# Author
author:
  name:             'Colin Seymour'
  twitter:          'lildude'
  description:      "Colin is a running, jumping, hopping, skipping genius of a guy."

# Google
google_analytics:   'UA-118457-1'
google-site-verification: o3ndy3P367VLktFTahXr93p9eecE21pdlC70nLMMJh0

# SASS/SCSS
sass:
  sass_dir:         _scss
  style:            compressed

# HTML Compression
compress_html:
  clippings:        all
  comments:         ["<!-- ", " -->"]
  endings:          all
  ignore:
    envs:           []

# Configure RedCarpet
redcarpet:
  extensions:       [tables, autolink, strikethrough, footnotes, superscript]

# Plugins
gems:
  - jemoji
  - jekyll-sitemap

# Don't copy these files to the generated site
exclude: [CNAME, Gemfile, Gemfile.lock, LICENSE.md, Rakefile, README.md]
