# Dependencies
markdown:           redcarpet
highlighter:        pygments

# Permalinks
permalink:          :title

# Setup
title:              Colin Seymour
tagline:            Woh ho ho, it's magic
meta_description:   "lildude rocking the tech world."
baseurl:            /
url:                https://colinseymour.co.uk
logo:               true
paginate:           15

# Author
author:
  name:             'Colin'
  twitter:          'lildude'
  description:      "Colin is running, jumping, hopping, skipping genius of a guy."

# Google
google_analytics:   'UA-118457-1'
google-site-verification: o3ndy3P367VLktFTahXr93p9eecE21pdlC70nLMMJh0

# SASS/SCSS
sass:
  sass_dir:         _scss
  style:            compressed

# HTML Compression
compress_html:
  clippings:        all
  comments:         ["<!-- ", " -->"]
  endings:          all
  ignore:
    envs:           []

# Plugins
#gems:
#  -jemoji

# Don't copy these files to the generated site
exclude: [CNAME, Gemfile, Gemfile.lock, LICENSE.md, Rakefile, README.md]
