# Dependencies
markdown:           kramdown
highlighter:        rouge

# Permalinks
permalink:          :title

# Setup
title:              Colin Seymour
description:        You Know This Boogie Is For Real
baseurl:            ""
url:                https://colinseymour.co.uk
logo:               "true"
lang:               en-GB
theme:              minima-dude

dns_prefetch:
  - images.weserv.nl
  - d33wubrfki0l68.cloudfront.net

# Defaults for the entire site - this ensures my notes and photos which use implied titles don't get a title in the feed
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      title: ""

# Author
author:             'lildude'
twitter:
  username:         'lildude'

microblog:
  username:         lildude
  site:             /cs # Needs the slash cos I'm lazy in my theme.
webmentions:        colinseymour.co.uk

# SASS/SCSS
sass:
  sass_dir:         _scss
  style:            compressed

# HTML Compression
compress_html:
  clippings:        all
  comments:         ["<!-- ", " -->"]
  #endings:         all # Commented out in favour of selecting all _except_ p as this breaks formatting
  endings:          [html, head, body, li, dt, dd, rt, rp, optgroup, option, colgroup, caption, thead, tbody, tfoot, tr, td, th]
  startings:        [html, body]  # We need the <head> as Google Site verification needs it.
  ignore:
    envs:           [test, local, development]
  profile:          false

kramdown:
  input:            GFM
  smart_quotes:     ["apos", "apos", "quot", "quot"]  # Don't do smart quoting by replacing like for like.

# Theme settings
minima_dude:
  date_format: "%-d %b %Y"
  show_author: false

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-loading-lazy
  - jekyll-include-cache
  - jekyll-image-cache

# Plugin-specific configs
feed:
  path: atom.xml
  use_excerpts: false

# Don't copy these files to the generated site
exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - LICENSE
  - Rakefile
  - README.md
  - vendor
  - sitespeed-result
  - script
  - .jekyll-cache
  - package.json
  - package-lock.json
  - postcss.config.js
  - tmp
# Don't attempt to process these - ie leave as-is
keep_files:
  - assets
  - img