# Dependencies
markdown:           kramdown
highlighter:        rouge

# Permalinks
permalink:          :title

# Setup
title:              Colin Seymour
description:        You Know This Boogie Is For Real
baseurl:            ""
url:                https://colinseymour.co.uk
logo:               "true"
lang:               en-GB
theme:              minima-dude
#paginate:           10

# Author
author:             'Colin Seymour'
twitter:
  username:         'lildude'

microblog:
  username:         lildude
# SASS/SCSS
sass:
  sass_dir:         _scss
  style:            compressed

# HTML Compression
compress_html:
  clippings:        all
  comments:         ["<!-- ", " -->"]
  #endings:         all # Commented out in favour of selecting all _except_ p as this breaks formatting
  endings:          [html, head, body, li, dt, dd, rt, rp, optgroup, option, colgroup, caption, thead, tbody, tfoot, tr, td, th]
  startings:        [html, body]  # We need the <head> as Google Site verification needs it.
  ignore:
    envs:           [test, local]
  profile:          false

kramdown:
  input:            GFM
  smart_quotes:     ["apos", "apos", "quot", "quot"]  # Don't do smart quoting by replacing like for like.

# Plugins
plugins:
  - jekyll-sitemap
  #- jekyll-json-feed
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-loading-lazy
  #- jekyll-paginate

# Plugin-specific configs
feed:
  path: atom.xml

# Don't copy these files to the generated site
exclude: [CNAME, Gemfile, Gemfile.lock, LICENSE.md, Rakefile, README.md, vendor, img/src, script]
# Don't attempt to process these - ie leave as-is
keep_files: [assets, img]
