name: Col's Tech
description: Woh ho ho, it's magic
meta_description: "lildude rocking the tech world."

markdown: redcarpet
highlighter: pygments
logo: true
paginate: 15
baseurl: /
domain_name: 'http://yourblog-domain.com'
google_analytics: 'UA-XXXXXXXX-X'

# Permalinks
permalink:        :title

sass:
  sass_dir:       _scss
  style:          compressed

# Details for the RSS feed generator
url:            'blog url'
author:         'Colin'

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: []
